name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: IO Scan
      uses: sig-chakrava/io-scan@v1-beta.4
      with:
        stage: "IO"
        ioServerHost: ${{secrets.IO_SERVER_URL}}
        ioServerPort:  80
        ioServerToken: ${{secrets.IO_SERVER_TOKEN}}        
        workflowServerUrl: ${{secrets.WORKFLOW_SERVER_URL}}
        workflowServerToken: ${{secrets.WORKFLOW_SERVER_TOKEN}}
        prescriptionDownloadURL: ${{secrets.PRESCRIPTION_DOWNLOAD_URL}}
        
    - name: Static Analysis with Polaris
     # if: ${{steps.prescription.outputs.sastScan == 'true'}}
      run: |
        export POLARIS_SERVER_URL=${{secrets.POLARIS_SERVER_URL}}
        export POLARIS_ACCESS_TOKEN=${{secrets.POLARIS_ACCESS_TOKEN}}
        wget -q ${{secrets.POLARIS_SERVER_URL}}/api/tools/polaris_cli-linux64.zip

    - name: Synopsys Intelligent Security Scan
     # if: ${{steps.prescription.outputs.sastScan == 'true' || steps.prescription.outputs.scaScan == 'true'}}
      uses: synopsys-sig/intelligent-security-scan@v1
      with:
        ioServerHost: ${{secrets.IO_SERVER_URL}}
        ioServerPort:  80
        ioServerToken: ${{secrets.IO_SERVER_TOKEN}}
        workflowServerUrl: ${{secrets.WORKFLOW_SERVER_URL}}
        workflowServerToken: ${{secrets.WORKFLOW_SERVER_TOKEN}}
        prescriptionDownloadURL: ${{secrets.PRESCRIPTION_DOWNLOAD_URL}}
        stage: "WORKFLOW"      