name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: IO Scan
      uses: sig-chakrava/io-scan@v1-beta.4
      with:
        stage: "IO"
        ioServerHost: ${{secrets.IO_SERVER_URL}}
        ioServerPort:  80
        ioServerToken: ${{secrets.IO_SERVER_TOKEN}}        
        workflowServerUrl: ${{secrets.WORKFLOW_SERVER_URL}}
        workflowServerToken: ${{secrets.WORKFLOW_SERVER_TOKEN}}
        prescriptionDownloadURL: ${{secrets.PRESCRIPTION_DOWNLOAD_URL}}

    - name: Synopsys Intelligent Security Scan
     # if: ${{steps.prescription.outputs.sastScan == 'true' || steps.prescription.outputs.scaScan == 'true'}}
      uses: synopsys-sig/intelligent-security-scan@v1
      with:
        ioServerHost: ${{secrets.IO_SERVER_URL}}
        ioServerPort:  80
        ioServerURL: ${{secrets.IO_SERVER_URL}}
        ioServerToken: ${{secrets.IO_SERVER_TOKEN}}
        workflowServerUrl: ${{secrets.WORKFLOW_SERVER_URL}}
        workflowServerToken: ${{secrets.WORKFLOW_SERVER_TOKEN}}
        prescriptionDownloadURL: ${{secrets.PRESCRIPTION_DOWNLOAD_URL}}
        stage: "WORKFLOW"      